# Урок_3

In [2]:
import numpy as np
import scipy.linalg


In [1]:

def matrix_mult(Matrix_a, Matrix_b):
    if len(Matrix_a[0]) == len(Matrix_b):
        Matrix_res = np.zeros((len(Matrix_b), len(Matrix_a[0])))
        for i in range(len(Matrix_res)):
            for j in range(len(Matrix_res[0])):
                scalar = []
                for _ in range(len(Matrix_b)):
                    scalar.append(Matrix_a[i][_]*Matrix_b[_][j])
                    Matrix_res[i][j] = sum(scalar)
        return Matrix_res
    else:
        return f"Длина матрицы { Matrix_a} не соответствует глубине матрицы { Matrix_b}"


Matrix_a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Matrix_b = [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
Matrix_res = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
print(matrix_mult(Matrix_a, Matrix_b))

print(np.dot(Matrix_a, Matrix_b))


[[ 84.  90.  96.]
 [201. 216. 231.]
 [318. 342. 366.]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


а) A — матрица  4x2, B — матрица  4x2; - не определены
б) A — матрица 2х5, B — матрица ;5х3  AB определена 2x3
в) A — матрица 8х3, B — матрица ;3х8 АВ 8x8 и ВА 3x3 определены
г) A — квадратная матрица  4х4, B — квадратная матрица  4х4. АВ и ВА определены 4x4

2. Найти сумму и произведение матриц А и  В

In [3]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(A+B)
print(np.dot(A, B))
print(np.dot(B, A))

[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3A -2B+4C  для матриц

In [6]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(3*A -2*B+4*C)

[[ 11  -5]
 [  9 -12]]


4. Дана матрица A, вычислить:

In [13]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(A.T)
print(np.dot(A, A.T))
print(np.dot(A.T, A))

[[ 4  5  2]
 [ 1 -2  3]]
[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


квадратные и симметричные

# Урок_4

1. Вычислить определитель:

а)

det(
sin x     -cos x
cos x      sinx
) = 1

b)

det(
4    2    3
0    5    1
0    0    9
) = 4*5*9 = 180

In [5]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(A)

180.0

c)

In [8]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
round(np.linalg.det(A), 2)

0.0

2. Определитель матрицы A равен 4. Найти:

a)

det(A**2) = det(A)*det(A)=16

b)

det(A**T) = det(A) = 4

c)

det(2*A) (Разберем на примере)

Следовательно det(2*A) = 4*2**n (где n это размер матрицы)

3. Доказать, что матрица вырожденная

det(
    −2    7    -3
    4    -14    6
    −3    7    13
) =
(умножаю 1-ю строку на 2 и плюсую ко 2-й строке)
det(
     −2    7    -3
     0    0     0
    −3    7    13
) = 0

4. Найти ранг матрицы:

In [4]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(A)

2

rank(
    1, 2, 3
    1, 1, 1
    2, 3, 4
) =
rank(
    1, 2, 3
    1, 1, 1
) = 
rank(
    1, 2, 3
    0,-1,-2
) = 2

In [ ]:
3-я строка явпяется суммой 1-й и 2-й)